#!/usr/bin/env python3
"""
Phase 5 Stage 2: Load comment analysis results into videos.comment_analysis.

Reads comment_analysis_<timestamp>.json produced by Stage 1 and adds the
comment_analysis field to each matching document in the existing videos
collection using $set. Existing fields such as embeddings and metadata are not
modified at all.

Videos whose is_soccer_related value is judged to be false are treated as videos
unrelated to soccer (for example, cricket/basketball/volleyball videos that were
mistakenly matched by a search.list "World Cup" query). Instead of applying
$set, those videos are completely deleted from the videos collection. Analysis
results where the is_soccer_related field does not exist (generated by older
versions of 3_analyze_comments.py) are handled as before and are not deleted for
backward compatibility.

[Second half of the two-stage pipeline] This script does not call the Gemini API.
It matches records by video_id, so the operation is idempotent.

Prerequisites:
    pip install "pymongo[srv]"
    export MONGODB_URI='mongodb+srv://<user>:<password>@xxxx.mongodb.net/'

Usage:
    python load_comment_analysis.py [path to comment_analysis_*.json]
"""

import os
import sys
import glob
import json
import shutil
from datetime import datetime, timezone

from pymongo import MongoClient, UpdateOne, DeleteOne
from pymongo.server_api import ServerApi
from pymongo.errors import ConnectionFailure, OperationFailure, ConfigurationError, BulkWriteError

DB_NAME = "soccertube"
COLL_NAME = "videos"

from dotenv import load_dotenv
from pathlib import Path
SCRIPT_DIR = Path(__file__).parent
load_dotenv(SCRIPT_DIR.parent / 'app' / 'soccer_agent' / '.env')

DB_NAME = os.environ.get("SOCCER_DB_NAME", "soccertube")
COLL_NAME = os.environ.get("SOCCER_COLL_NAME", "videos")


def find_input_path() -> str:
    if len(sys.argv) > 1:
        return sys.argv[1]
    hits = sorted(glob.glob("comment_analysis_*.json"))
    if not hits:
        print("ERROR: comment_analysis_*.json was not found. Please pass the path as an argument.",
              file=sys.stderr)
        sys.exit(1)
    return hits[-1]


def archive_run_files():
    """Move the intermediate JSON files used in this run to data/<YYYYMMDD>/.
    The latest file for each pattern, which corresponds to this run, is moved.
    build_stats_page.py also searches data/<date>/, so statistics can still be generated after archiving."""
    from pathlib import Path
    date_dir = Path("data") / datetime.now().strftime("%Y%m%d")
    date_dir.mkdir(parents=True, exist_ok=True)
    patterns = [
        "data/phase2_video_ids_*.json",
        "data/phase3_metadata_*.json",
        "data/phase7_with_buzz_score_*.json",
        "data/phase4_comments_*.json",
        "videos_embedded_*.json",        # Output from 1_embed in the current directory
        "comment_analysis_*.json",       # Output from 3_analyze in the current directory
    ]
    moved = []
    for pat in patterns:
        hits = sorted(glob.glob(pat))   # data/<date>/ is excluded because this is a non-recursive glob.
        if not hits:
            continue
        src = hits[-1]                  # Latest file, corresponding to this run
        dest = date_dir / Path(src).name
        try:
            shutil.move(src, dest)
            moved.append(dest.name)
        except OSError as e:
            print(f"  WARNING: Failed to archive {src}: {e}", file=sys.stderr)
    print(f"\nArchive: moved {len(moved)} intermediate JSON files to {date_dir}/.")
    for name in moved:
        print(f"    - {name}")


def main() -> int:
    uri = os.environ.get("MONGODB_URI")
    if not uri:
        print("ERROR: MONGODB_URI is not set.", file=sys.stderr)
        return 1

    path = find_input_path()
    print(f"Input file: {path}")
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    analyses = data.get("analyses", {})
    if not analyses:
        print("ERROR: analyses is empty.", file=sys.stderr)
        return 1
    print(f"Load target: {len(analyses)} analysis results")

    try:
        mclient = MongoClient(uri, server_api=ServerApi("1"), serverSelectionTimeoutMS=5000)
        mclient.admin.command("ping")
    except (ConnectionFailure, OperationFailure, ConfigurationError) as e:
        print(f"ERROR: MongoDB connection failed: {e}", file=sys.stderr)
        return 1
    coll = mclient[DB_NAME][COLL_NAME]

    # Set comment_analysis on the matching document by video_id.
    # Videos where is_soccer_related == False are deleted from the videos collection.
    # Analysis results in the old format where the field does not exist are handled
    # as updates as before and are not deleted for backward compatibility.
    to_update = {}
    to_delete_ids = []
    for vid, analysis in analyses.items():
        is_soccer_related = analysis.get("is_soccer_related")
        if is_soccer_related is False:
            to_delete_ids.append(vid)
        else:
            to_update[vid] = analysis

    print(f"\nBreakdown: update target={len(to_update)} records / "
          f"delete target because non-soccer-related={len(to_delete_ids)} records")
    if to_delete_ids:
        print("  Delete target video_id: " + ", ".join(to_delete_ids))

    now = datetime.now(timezone.utc)

    if to_update:
        print("\nUpdating videos.comment_analysis using $set with video_id matching...")
        ops = [
            UpdateOne(
                {"video_id": vid},
                {"$set": {"comment_analysis": analysis, "last_analyzed": now}},
            )
            for vid, analysis in to_update.items()
        ]
        try:
            res = coll.bulk_write(ops, ordered=False)
        except BulkWriteError as e:
            print(f"ERROR: Bulk update failed: {e.details}", file=sys.stderr)
            return 1

        matched = res.matched_count
        modified = res.modified_count
        print(f"  matched={matched}, modified={modified}")

        # Identify video_ids that did not match because they do not exist in videos. This should normally be 0.
        if matched < len(to_update):
            existing_ids = set(coll.distinct("video_id"))
            unmatched = [vid for vid in to_update if vid not in existing_ids]
            print(f"  WARNING: {len(unmatched)} video_ids did not match because they do not exist in videos: {unmatched}",
                  file=sys.stderr)
    else:
        print("\nThere are 0 update targets, so $set is skipped.")

    if to_delete_ids:
        print("\nDeleting non-soccer-related videos from the videos collection...")
        delete_ops = [DeleteOne({"video_id": vid}) for vid in to_delete_ids]
        try:
            del_res = coll.bulk_write(delete_ops, ordered=False)
        except BulkWriteError as e:
            print(f"ERROR: Bulk delete failed: {e.details}", file=sys.stderr)
            return 1
        print(f"  deleted_count={del_res.deleted_count}")
        if del_res.deleted_count < len(to_delete_ids):
            print(f"  WARNING: {len(to_delete_ids)} delete targets, but actually deleted "
                  f"{del_res.deleted_count} records. Some records may not have existed already.", file=sys.stderr)

    # Verification: count documents that have comment_analysis.
    with_analysis = coll.count_documents({"comment_analysis": {"$exists": True}})
    total = coll.count_documents({})
    print(f"\nVerification: {with_analysis} / {total} records have comment_analysis")

    mclient.close()
    print(f"\nStage 2 complete. Added sentiment analysis results to {len(to_update)} videos "
          f"and deleted {len(to_delete_ids)} videos as non-soccer-related.")

    # Move the intermediate JSON files used in this run to data/<date>/ after successful completion.
    archive_run_files()
    return 0


if __name__ == "__main__":
    sys.exit(main())
